import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreatePasswordResetTokens1776328717754 implements MigrationInterface {
  name = 'CreatePasswordResetTokens1776328717754';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "public"."password_reset_tokens" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "expires_at" TIMESTAMP NOT NULL,
        "used" BOOLEAN NOT NULL DEFAULT false,
        "token" VARCHAR NOT NULL,
        "user_id" VARCHAR(36) NOT NULL,
        "created_at" TIMESTAMP NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(
      `
        ALTER TABLE "public"."password_reset_tokens"
        ADD CONSTRAINT "FK_password_reset_tokens_user_id"
        FOREIGN KEY ("user_id")
        REFERENCES "public"."users" ("id")
        DEFERRABLE INITIALLY IMMEDIATE
      `,
    );
    await queryRunner.query(
      `
        CREATE UNIQUE INDEX "IDX_password_reset_tokens_token_unique"
        ON "public"."password_reset_tokens" ("token")
      `,
    );
    await queryRunner.query(
      `
        CREATE INDEX "IDX_password_reset_tokens_user_id"
        ON "public"."password_reset_tokens" ("user_id")
      `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX "public"."IDX_password_reset_tokens_user_id"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_password_reset_tokens_token_unique"`,
    );
    await queryRunner.query(`DROP TABLE "public"."password_reset_tokens"`);
  }
}
